# .streamlit/secrets.toml

[connections.dbx]
type="sql"
dialect = "mysql"
host = "localhost"
port = 3306
database = "device_data"
username = "root"
password = "Cns_2016!!"

[mysql]
host = "localhost"
port = 3306
database = "device_data"
user = "root"
password = "Cns_2016!!"
